### PR TITLE
CA-9488: add codeowners for source plugins

### PR DESCRIPTION
**Pull request by dietmar-91**
- With this PR code owners will be added to this repository
- Please double-check if owners are configured correctly

### CODE REVIEW

**Review by christian-kreuzberger-dtx — APPROVED** [review]

**Review by MrManny — APPROVED** [review]
LGTM! :)

**Comment by MrManny** [comment]
Just one note: GitHub flags the user Jai28 as unknown.

**Comment by dietmar-91** [comment]
> Just one note: GitHub flags the user Jai28 as unknown.

Yes your are right and I saw that. But I am not sure why because it should be the correct GitHub username.

**Comment by christian-kreuzberger-dtx** [comment]
> > Just one note: GitHub flags the user Jai28 as unknown.
> 
> Yes your are right and I saw that. But I am not sure why because it should be the correct GitHub username.

It's because Jai does not have write access to this repo.

**Review by agrimmer — APPROVED** [review]

**Pull request merged**
